module.exports = {
  content: [
    "./views/**/*.hbs",
    "./views/*.hbs",
    "./public/**/*.js",
    "../app/views/**/*.hbs",
    "../app/views/*.hbs",
    "../app/public/**/*.js"
  ],
  safelist: [
    // Layout & Position
    'fixed',
    'absolute',
    'relative',
    'sticky',
    'bottom-0',
    'top-0',
    'left-0',
    'right-0',
    'z-40',
    'z-50',
    'w-full',
    // Flexbox & Grid
    'flex',
    'flex-1',
    'flex-col',
    'items-center',
    'items-stretch',
    'justify-between',
    'justify-end',
    'gap-0',
    'gap-2',
    'gap-3',
    'gap-4',
    // Sizing
    'h-16',
    'w-5',
    'h-5',
    // Spacing
    'px-6',
    'px-8',
    'py-4',
    'mb-0.5',
    'mt-6',
    // Borders
    'border',
    'border-t',
    'border-r',
    'border-gray-200',
    'shadow-lg',
    // Backgrounds
    'bg-white',
    'bg-slate-50',
    // Text
    'text-xs',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-center',
    'text-gray-500',
    'text-gray-900',
    'text-green-600',
    'text-red-600',
    'text-purple-600',
    'font-medium',
    'font-bold',
    // Transitions
    'transition-all',
    'duration-300',
    // Button variants
    'btn',
    'btn-primary',
    'btn-secondary',
    'btn-outline',
    'btn-outline-secondary',
    'btn-outline-danger',
    'btn-ghost',
    'btn-ghost-primary',
    'btn-danger',
    'btn-soft-primary',
    'btn-soft-secondary',
    // Button sizes
    'btn-xs',
    'btn-sm',
    'btn-md',
    'btn-lg',
    'btn-xl',
    'btn-icon',
    'btn-icon-sm',
    'btn-icon-lg',
    // Cards
    'card',
    'card-hover',
    'card-compact',
    'card-gradient',
    'card-glass',
    // Badges
    'badge',
    'badge-widiba',
    'badge-relaxbanking',
    'badge-traderepublic',
    'badge-success',
    'badge-warning',
    'badge-danger',
    'badge-info',
    'badge-subtle',
    // Amounts
    'amount-in',
    'amount-out',
    'amount-zero',
    'amount-large',
    'amount-card',
    'amount-card-label',
    'amount-card-value',
    // Forms
    'form-input',
    'form-select',
    'form-label',
    'form-helper',
    'form-error',
    'input-fintech',
    'label-fintech',
    // Alerts
    'alert',
    'alert-success',
    'alert-error',
    'alert-warning',
    'alert-info',
    'alert-icon',
    'alert-content',
    'alert-title',
    'alert-message',
    // Progress
    'progress-bar',
    'progress-bar-fill',
    'progress-bar-indeterminate',
    // Upload
    'upload-progress-card',
    'upload-step',
    'upload-step-icon',
    // Spinners
    'spinner',
    'spinner-lg',
    // Navigation
    'nav-link',
    'nav-link-active',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#7C3AED',
          dark: '#6D28D9',
          light: '#A78BFA',
          subtle: '#EDE9FE',
        },
        accent: {
          DEFAULT: '#10B981',
          dark: '#059669',
          light: '#6EE7B7',
          subtle: '#D1FAE5',
        },
        success: '#10B981',
        danger: '#EF4444',
        warning: '#F59E0B',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
}
